### ISSUE TITLE
渲染的bug

### ISSUE THREAD

**Issue by MyAlphaGo** [aui/express-art-template#10]
有的时候能正常渲染，但是偶尔出现bug，渲染不成功，会被pre标签包裹

**Comment by aui** [comment]
art-template 代码里是没有 pre 的，你可以排查下

**Comment by MyAlphaGo** [comment]
不好意思，因为我跨域写了res.header('Content-Type', 'application/json;charset=utf-8');，而且我在刷新的时候没有强制刷新，所有导致偶尔能渲染，偶尔不能渲染的假象，十分抱歉。




------------------ 原始邮件 ------------------
发件人: "糖饼"<notifications@github.com>;
发送时间: 2019年8月31日(星期六) 晚上8:40
收件人: "aui/express-art-template"<express-art-template@noreply.github.com>;
抄送: "情殇"<2774598495@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [aui/express-art-template] 渲染的bug (#10)




art-template 代码里是没有 pre 的，你可以排查下
