### ISSUE TITLE
发现一个配置bug

### ISSUE THREAD

**Issue by hunterlord** [aui/express-art-template#3]
感觉楼主对这个express模块不是很用心啊

template.defaults.imports是个对象并且包含两个方法
如果定义了view options 的imports 那么引擎就报错了

我改了如下后正常了，不知道是不是有没考虑到的，希望楼主修正，最近给同时介绍了你的模板引擎，大家都很是喜欢

if (data.settings && data.settings['view options']) {                                                                                               
         if (data.settings['view options'].imports) {                                                                                                      
           Object.assign(options.imports,data.settings['view options'].imports);                                                                                                                                      
           delete data.settings['view options'].imports;                                                                                                   
         }                                                                                                                                                 
         options = options.$extend(data.settings['view options']);

**Comment by aui** [comment]
v4.9.1 已经修复

**Comment by hunterlord** [comment]
谢谢
