### ISSUE TITLE
渲染测试是指的什么

### ISSUE THREAD

**Issue by Yenuo** [aui/express-art-template#5]
https://aui.github.io/art-template/rendering-test/?test=%7B%22length%22%3A20%2C%22calls%22%3A2048%2C%22escape%22%3Atrue%7D
这个具体测试的是什么时间？能帮我解答下吗？

**Comment by aui** [comment]
顾名思义：渲染时间，你可以理解为”实验室“的测试结果。实际上在服务器中运行，还得考虑大型字符串传输的时间，这里可能会与”实验室“的测试结果有差距
